### ISSUE TITLE
百度云链接失效了 能否补一下 感谢

### ISSUE THREAD

**Issue by jeremisty99** [YinGuoX/OpenCV_Base#1]

**Comment by YinGuoX** [comment]
之前忙勿怪，现已更新



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YinGuoX/OpenCV_Base"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月14日(星期二) 凌晨0:09
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [YinGuoX/OpenCV_Base] 百度云链接失效了 能否补一下 感谢 (#1)





 
Closed #1.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
